{% set name = "Cheroot" %}
{% set version = "6.6.0" %}
{% set bundle = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash = "c4e1215e02fc95febcef3033cacd2a7d6be320a0206976f7e254fc9b216ada1b" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name|lower }}-{{ version }}.{{ bundle }}
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name|lower }}-{{ version }}.{{ bundle }}
  {{ hash_type }}: {{ hash }}

build:
  noarch: python
  number: 0
  {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python
    - pip
    - setuptools_scm >=1.15.0
    - setuptools_scm_git_archive >=1.0

  run:
    - python
    - six >=1.11.0
    - more-itertools >=2.6
    - backports.functools_lru_cache

test:
  imports:
    - cheroot
    - cheroot.test


about:
  home: http://www.cherrypy.org
  license: BSD 3-Clause
  license_family: BSD
  license_file: LICENSE.md
  summary: 'Highly-optimized, pure-python HTTP server'
  dev_url: https://github.com/cherrypy/cheroot
  doc_url: https://cheroot.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - pmlandwehr
