{% set name = "Cheroot" %}
{% set version = "10.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0]|lower }}/{{ name|lower }}/{{ name|lower }}-{{ version }}.tar.gz
  sha256: e0b82f797658d26b8613ec8eb563c3b08e6bd6a7921e9d5089bd1175ad1b1740

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - cheroot = cheroot.cli:main

requirements:
  host:
    - python >=3.6
    - pip
    - setuptools_scm >=7.0.0
    - setuptools_scm_git_archive >=1.0
  run:
    - python >=3.6
    - six >=1.11.0
    - more-itertools >=2.6
    - jaraco.functools

test:
  imports:
    - cheroot
    - cheroot.test
  commands:
    - cheroot -h

about:
  home: https://cheroot.cherrypy.dev
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.md
  summary: Highly-optimized, pure-python HTTP server
  dev_url: https://github.com/cherrypy/cheroot
  doc_url: https://cheroot.cherrypy.dev

extra:
  recipe-maintainers:
    - pmlandwehr
    - carlodri
