{% set name = "Cheroot" %}
{% set version = "8.5.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0]|lower }}/{{ name|lower }}/{{ name|lower }}-{{ version }}.tar.gz
  sha256: 177b4efe6eee42d899cd6e19b5e5985994cd160e067d1a4f28231e296162e5ea

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - cheroot = cheroot.cli:main

requirements:
  host:
    - python >=3.6
    - pip
    - setuptools_scm >=1.15.0
    - setuptools_scm_git_archive >=1.0
  run:
    - python >=3.6
    - six >=1.11.0
    - more-itertools >=2.6
    - jaraco.functools

test:
  imports:
    - cheroot
    - cheroot.test
  commands:
    - cheroot -h

about:
  home: http://www.cherrypy.org
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.md
  summary: Highly-optimized, pure-python HTTP server
  dev_url: https://github.com/cherrypy/cheroot
  doc_url: https://cheroot.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - pmlandwehr
    - carlodri
