{% set name = "Cheroot" %}
{% set version = "11.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0]|lower }}/{{ name|lower }}/{{ name|lower }}-{{ version }}.tar.gz
  sha256: bfb70c49663f63b0440f2b54dbc6b0d1650e56dfe4e2641f59b2c6f727b44aca

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - cheroot = cheroot.cli:main

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools_scm >=7.0.0
    - setuptools_scm_git_archive >=1.0
    - setuptools
  run:
    - python >={{ python_min }}
    - six >=1.11.0
    - more-itertools >=2.6
    - jaraco.functools

test:
  requires:
    - python {{ python_min }}
  imports:
    - cheroot
    - cheroot.test
  commands:
    - cheroot -h

about:
  home: https://cheroot.cherrypy.dev
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.md
  summary: Highly-optimized, pure-python HTTP server
  dev_url: https://github.com/cherrypy/cheroot
  doc_url: https://cheroot.cherrypy.dev

extra:
  recipe-maintainers:
    - pmlandwehr
    - carlodri
