{%set name = "Cheroot" %}
{%set version = "5.5.0" %}
{%set compress_type = "tar.gz" %}
{%set hash_type = "sha256" %}
{%set hash = "59e349f91b9230930f7078646bb92b3a5b0f9cf19a6ff949777409fd289a1eba" %}
{%set build = 0 %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name|lower }}-{{ version }}.{{ compress_type }}
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name|lower }}-{{ version }}.{{ compress_type }}
  {{ hash_type }}: {{ hash }}

build:
  number: {{ build }}
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools
    - setuptools_scm >=1.15.0

  run:
    - python
    - six

test:
  imports:
    - cheroot
    - cheroot.test


about:
  home: http://www.cherrypy.org
  license: BSD 3-Clause
  license_family: BSD
  license_file: LICENSE.md
  summary: 'Highly-optimized, pure-python HTTP server'
  dev_url: https://github.com/cherrypy/cheroot
  doc_url: http://www.cherrypy.org

extra:
  recipe-maintainers:
    - pmlandwehr
